apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-dogs-app
  template:
    metadata:
      labels:
        app: cats-dogs-app
    spec:
        containers:
        - name: cats-dogs-container
          image: ghcr.io/2024ac05006/cats-dogs-service:latest
          ports:
          - containerPort: 8000
          
          # Add this readiness probe block
          readinessProbe:
            httpGet:
              path: /  # Update this to /health or /ping if your API uses one
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3